version: 2
updates:
  # Update dependencies in `requirements.txt`
  - package-ecosystem: "pip"
    directory: "/"  # Directory where requirements.txt is located
    schedule:
      interval: "weekly"  # Frequency of checks (daily, weekly, or monthly)

  # Update dependencies in pyproject.toml and poetry.lock
  - package-ecosystem: "poetry"
    directory: "/"  # Directory where pyproject.toml is located
    schedule:
      interval: "weekly"

  # Update dependencies in Conda's environment.yml
  - package-ecosystem: "conda"
    directory: "/"  # Directory where environment.yml is located
    schedule:
      interval: "weekly"

  # Update GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
