name: Run Tests and Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-xdist

      - name: Run unit tests with coverage
        run: |
          pytest -m unit --cov=zrad --cov-append

      - name: Upload coverage data (unit)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-unit
          path: .coverage

      - name: Upload unit coverage report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-unit
          path: htmlcov/

  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-xdist

      - name: Run integration tests with coverage
        run: |
          pytest -m integration --cov=zrad --cov-append

      - name: Upload coverage data (integration)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-integration
          path: .coverage

      - name: Upload integration coverage report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-integration
          path: htmlcov/

  coverage_report:
    name: Generate Combined Coverage Report
    runs-on: ubuntu-latest
    needs: [unit_tests, integration_tests]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install coverage.py
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      # Download both unit and integration coverage artifacts
      - name: Download coverage data from unit tests
        uses: actions/download-artifact@v4
        with:
          name: coverage-data-unit
          path: coverage_data

      - name: Download coverage data from integration tests
        uses: actions/download-artifact@v4
        with:
          name: coverage-data-integration
          path: coverage_data

      - name: Combine coverage data
        run: |
          coverage combine coverage_data
          coverage report -m --skip-covered
          coverage html

      - name: Upload combined coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-combined
          path: htmlcov/
